### ISSUE TITLE
What is the name of this algorithm

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/sorting-assignment-bjornvoesten#1]
I would like to know the name of this sorting algorithm. Can you find a reference to a description of this algorithm?

**Comment by bjornvoesten** [comment]
Als ik het goed heb begrepen is dit het selection sort algoritme. 
Bron: https://en.wikipedia.org/wiki/Selection_sort

**Comment by dvberkel** [comment]
Dit klopt deels. Zoals ook in jouw bron te lezen valt is selection sort an _in-place_ sorteer algorithme. Dat betekend dat de input array ook wordt gebruikt om het resultaat mee op te bouwen. Dit kan voordelen met zich mee brengen.

Denk bijvoorbeeld even aan `List` uit Elm. Voor de volledigheid is hieronder een gangbare definitie herhaald

```elm
type List a
    = Empty
    | Cons a (List a)
```

Een van de onderdelen van jouw algoritme is het toevoegen van een element aan het einde van de lijst. Hoeveel stappen zijn daar voor nodig? O(n)

Dat zou invloed kunnen hebben op de geclaimde complexiteit van het gehele algoritme

**Comment by bjornvoesten** [comment]
@dvberkel Kan dit issue gesloten worden en de assignment gemarkeerd als goedgekeurd?
